# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ebfa664dc1964c9f6ef6f7672d34d9ca2e2f3c0f874964c7aaad16631c1b125ede036542265d7f5dd5253cd90b24a392ec20e1e44f20e12e241a22cd9117003

test:
  secret_key_base: 38effb00b2d09d8dc1f46d239d370723790b97d73d8239ba0c74430f7f5400b29b09b1b4056baf6dda6e919dd0184e67c2e2d747532bb81aa263db6baed583d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
